spring.application.name=Assignment15
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/ECom_db
spring.datasource.username=postgres
spring.datasource.password=qwerty05.#Ab
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
