spring.application.name=Assignment14
server.port=8080
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:Task14
spring.datasource.driverClassName=org.h2.Driver
logging.level.com.example.Assignment14.controller=DEBUG


